---
title: "PCP study"
author: "Akihiro Shiroshita, MD, MPH"
date: "`r Sys.time()`"
output: 
    word_document:
      toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}
packages = c("here",
             "readr",
             "readxl",
             "tableone",
             "tidyverse",
             "tidylog",
             "lubridate",
             "ggplot2",
             "RColorBrewer",
             "ggplotgui",
             "ggthemes",
             "broom",
             "survival",
             "JM",
             "survminer",
             "ggfortify",
             "magrittr",
             "rms",
             "lme4",
             "ggeffects"
             )

#install.packages("spDataLarge", repos = "https://nowosad.r-universe.dev")
package.check <- lapply(packages, FUN = function(x){
  if (!require(x, character.only = TRUE)){
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

knitr::opts_chunk$set(
	echo = FALSE,
	fig.pos = "t",
	message = FALSE,
	warning = FALSE,
	out.extra = ""
)
#rm(list=ls())
cols <- brewer.pal(6, "Set1")

theme_set(theme_bw())
mytheme <- function(...){
  theme(panel.grid.minor=element_blank(),
        plot.margin=unit(c(0.5, 0.5, 0.5, 0.5), 'lines'),
        axis.title.x=element_text(size=12, vjust=0),
        axis.title.y=element_text(size=12, vjust=1, angle=90),
        legend.title=element_text(size=12, face='bold'),
        legend.text=element_text(size=12),
        legend.position='top', legend.direction='horizontal', 
        legend.key=element_blank(),
        legend.key.width=unit(1.5,"cm"),
        legend.key.height=unit(0.35,'cm'),
        strip.text.y=element_text(size=12))}

plotResid <- function(x, y, col.lowess='red', ...){
  plot(x, y, ...)
  abline(h=0, col='gray', lwd=2)
  lines(lowess(x, y), col=col.lowess, lwd=2)}
plotQQ <- function(x, ...){
  qqnorm(x, main='')
  qqline(x, col='gray', lwd=2)}

setwd("C:/Users/shiroa1/OneDrive - Vanderbilt/PCP-prognosis")

data <- read_excel("input/pcp_study_cleaned.xlsx")
ids <- data %>% 
  distinct(id) %>% 
  pull()

beta_d <- read_rds('input/beta_d_after.rds')

beta_d <- beta_d %>% 
  mutate(log_result = log(result),
         result_100 = result/100,
         log_result_100 = log(result_100),
         interval = if_else(interval <= 0, 0.5, interval)) %>% 
  drop_na(age, sex, spo2) %>% 
  filter(interval <= 90)
  
include_ids_beta_d <- beta_d %>% 
  group_by(id) %>% 
  summarise(nrow = n()) %>% 
  ungroup() %>% 
  filter(nrow > 2) %>% 
  dplyr::select(id) %>% 
  pull()

beta_d <- beta_d %>% 
  filter(id %in% include_ids_beta_d)

ldh <- read_rds('input/ldh_after.rds')

ldh <- ldh %>% 
  mutate(log_result = log(result),
         result_100 = result/100,
         log_result_100 = log(result_100),
         interval = if_else(interval <= 0, 0.5, interval)) %>% 
  drop_na(age, sex, spo2) %>% 
  filter(interval <= 90)

include_ids_ldh <- ldh %>% 
  group_by(id) %>% 
  summarise(nrow = n()) %>% 
  ungroup() %>% 
  filter(nrow > 2) %>% 
  dplyr::select(id) %>% 
  pull() 

ldh <- ldh %>% 
  filter(id %in% include_ids_ldh)
```

Distribution of Beta-D

```{r}
ggplot(beta_d, aes(x = result)) +
  geom_density(position = 'identity', alpha = 0.8, adjust = 1) +
  facet_grid(~death90) +
  theme_bw()
```

Distribution of LDH

```{r}
ggplot(ldh, aes(x = result)) +
  geom_density(position = 'identity', alpha = 0.8, adjust = 1) +
  facet_grid(~death90) +
  theme_bw()
```

Change of Beta-D  

```{r}
summary(beta_d$diff)
```

Change of LDH  

```{r}
summary(ldh$diff)
```

## Selecting patients  

```{r}
ggplot(beta_d, aes(interval, result, group=id)) +
  geom_line(aes(color=factor(death90==0)), alpha=0.2) +
  geom_smooth(aes(interval, result, group=factor(death90), color=factor(death90==0)), se=FALSE, size=1.5) +
  scale_x_continuous(name='Days', limits=c(0,90)) +
  scale_y_continuous(name='Beta-D', limits=c(0,2000)) + 
  scale_color_manual(name='Outcome', values=cols[c(1,2)],
                     labels = c('Death', 'Censored')) +
  mytheme()
```

```{r}
beta_d <- within(beta_d, {
  status.lab <- ifelse(death90==0, 'Alive', 'Death')})

ggplot(beta_d, aes(interval-observation_time, result, group=id)) +
  facet_wrap( ~ status.lab) +
  geom_line(aes(color = status.lab), alpha=0.2) +
  geom_smooth(aes(interval-observation_time, result,
                  group=factor(death90), color=factor(death90)), se=FALSE, size=1.5) +
  scale_x_continuous(name='Time from end of follow-up (days)', limits=c(-90,0)) +
  scale_y_continuous(name='Beta-D', limits=c(0,1000)) + 
  scale_color_manual(name='Event', values=cols[c(2,1,2,1)]) +
  mytheme()
```

```{r}
ggplot(ldh, aes(interval, result, group=id)) +
  geom_line(aes(color=factor(death90==0)), alpha=0.2) +
  geom_smooth(aes(interval, result, group=factor(death90), color=factor(death90==0)), se=FALSE, size=1.5) +
  scale_x_continuous(name='Days', limits=c(0,90)) +
  scale_y_continuous(name='Beta-D', limits=c(0,2000)) + 
  scale_color_manual(name='Outcome', values=cols[c(1,2)],
                     labels = c('Death', 'Censored')) +
  mytheme()
```

```{r}
ldh <- within(ldh, {
  status.lab <- ifelse(death90==0, 'Alive', 'Death')})

ggplot(ldh, aes(interval-observation_time, result, group=id)) +
  facet_wrap( ~ status.lab) +
  geom_line(aes(color = status.lab), alpha=0.2) +
  geom_smooth(aes(interval-observation_time, result,
                  group=factor(death90), color=factor(death90)), se=FALSE, size=1.5) +
  scale_x_continuous(name='Time from end of follow-up (days)', limits=c(-90,0)) +
  scale_y_continuous(name='Beta-D', limits=c(0,1000)) + 
  scale_color_manual(name='Event', values=cols[c(2,1,2,1)]) +
  mytheme()
```

# Statistical analysis

## londitudinal analysis  

```{r}
ml_beta_d <- lme(log_result_100 ~ interval + age + sex + spo2,
                 random = ~ interval | id, data = beta_d)
summary(ml_beta_d)
```

```{r}
ml_ldh <- lme(log_result_100 ~ interval + age + sex + spo2,
                 random = ~ interval | id, data = ldh)
summary(ml_ldh)
```

## survival analysis  

```{r}
beta_d_id <- beta_d %>% distinct(id, .keep_all = TRUE)
ms_beta_d <- coxph(Surv(observation_time, death90) ~ age + sex + spo2,
             data=beta_d_id,
             x=TRUE)
```

```{r}
ldh_id <- ldh %>% distinct(id, .keep_all = TRUE)
ms_ldh <- coxph(Surv(observation_time, death90) ~ age + sex + spo2,
             data=ldh_id,
             x=TRUE)
```

## joint modeling of Beta-D   

```{r}
mj_beta_d <- jointModel(lmeObject=ml_beta_d,
                        survObject=ms_beta_d,
                        timeVar='interval',
                        method='weibull-PH-aGH')
summary(mj_beta_d)
```

```{r}
res <- summary(mj_beta_d)

res_long <- res[["CoefTable-Long"]] %>% as.data.frame() 
res_long <- res_long %>% 
  mutate(est = round(exp(Value), 3),
         lower = round(exp(Value - 1.96*Std.Err), 3),
         upper = round(exp(Value + 1.96*Std.Err), 3),
         p_value = round(`p-value`, 3)) %>% 
  dplyr::select(est, lower, upper, p_value) %>% 
  write.csv("memo/res_long.csv")
  
res_surv <- res[["CoefTable-Event"]] %>% as.data.frame() 
res_surv <- res_surv %>% 
  mutate(est = round(exp(Value), 3),
         lower = round(exp(Value - 1.96*Std.Err), 3),
         upper = round(exp(Value + 1.96*Std.Err), 3),
         p_value = round(`p-value`, 3)) %>%
  dplyr::select(est, lower, upper, p_value) %>% 
  write.csv("memo/res_surv_beta_d.csv")
```

```{r}
r_l_s <- residuals(mj_beta_d, process='Longitudinal', type='stand-Subject')
f_l_s <- fitted(mj_beta_d, process='Longitudinal', type='Subject')
r_l_m <- residuals(mj_beta_d, process='Longitudinal', type='stand-Marginal')
f_l_m <- fitted(mj_beta_d, process='Longitudinal', type='Marginal')
r_s <- residuals(mj_beta_d, process='Event', type='Martingale')
f_s <- fitted(mj_beta_d, process='Longitudinal', type='EventTime')
```

```{r}
par(mfrow=c(2,2), mar=c(5,5,1,1))
plotResid(f_l_s, r_l_s, xlab='Fitted values (subject)', ylab='Residuals (subject)')
plotQQ(r_l_s)
plotResid(f_l_m, r_l_m, xlab='Fitted values (marginal)', ylab='Residuals (marginal)')
plotResid(f_s, r_s, xlab='Fitted values (longitudinal)', ylab='Residuals (Martingale)')
```

```{r}

```


# Joint modeling of LDH  

```{r}
mj_ldh <- jointModel(lmeObject=ml_ldh,
                        survObject=ms_ldh,
                        timeVar='interval',
                        method='weibull-PH-aGH')
summary(mj_ldh)
```

```{r}
res <- summary(mj_ldh)

res_long <- res[["CoefTable-Long"]] %>% as.data.frame() 
res_long <- res_long %>% 
  mutate(est = round(exp(Value), 3),
         lower = round(exp(Value - 1.96*Std.Err), 3),
         upper = round(exp(Value + 1.96*Std.Err), 3),
         p_value = round(`p-value`, 3)) %>% 
  dplyr::select(est, lower, upper, p_value) %>% 
  write.csv("memo/res_long.csv")
  
res_surv <- res[["CoefTable-Event"]] %>% as.data.frame() 
res_surv <- res_surv %>% 
  mutate(est = round(exp(Value), 3),
         lower = round(exp(Value - 1.96*Std.Err), 3),
         upper = round(exp(Value + 1.96*Std.Err), 3),
         p_value = round(`p-value`, 3)) %>%
  dplyr::select(est, lower, upper, p_value) %>% 
  write.csv("memo/res_surv_ldh.csv")
```

```{r}
r_l_s <- residuals(mj_ldh, process='Longitudinal', type='stand-Subject')
f_l_s <- fitted(mj_ldh, process='Longitudinal', type='Subject')
r_l_m <- residuals(mj_ldh, process='Longitudinal', type='stand-Marginal')
f_l_m <- fitted(mj_ldh, process='Longitudinal', type='Marginal')
r_s <- residuals(mj_ldh, process='Event', type='Martingale')
f_s <- fitted(mj_ldh, process='Longitudinal', type='EventTime')
```

```{r}
par(mfrow=c(2,2), mar=c(5,5,1,1))
plotResid(f_l_s, r_l_s, xlab='Fitted values (subject)', ylab='Residuals (subject)')
plotQQ(r_l_s)
plotResid(f_l_m, r_l_m, xlab='Fitted values (marginal)', ylab='Residuals (marginal)')
plotResid(f_s, r_s, xlab='Fitted values (longitudinal)', ylab='Residuals (Martingale)')
```


